### ISSUE TITLE
[FE] UNIX Support

### ISSUE THREAD

**Issue by ghost** [SolDevelop/RPCC#1]
*What Is the new feature*
To support UNIX/BSD Systems such as MacOS and Debian
*do you think its possible*
It should be possible since PHP/Python are cross-platform high-level scripting languages.

**Comment by SolDevelop** [comment]
Hello yes its possible but i cant do all UNIX os i need to finish mac then start with linux after i done linux it will work with every linux distro  ok its coming soon!

**Comment by ghost** [comment]
What about BSD?

**Comment by SolDevelop** [comment]
> What about BSD?

BSD can be possible but it will take a bit of time

**Comment by SolDevelop** [comment]
MacOS Is Supported Now! Linux Is Coming Soon

**Comment by SolDevelop** [comment]
Hello Linux is Supported Now

**Comment by SolDevelop** [comment]
Only BSD is missing
