### ISSUE TITLE
[BUG] FUNDING.yml

### ISSUE THREAD

**Issue by ghost** [SolDevelop/RPCC#2]
*Error thats you get*

```
Some errors were encountered when parsing the FUNDING.yml file:

Unknown funding platform 'paypal'.
Learn more about formatting FUNDING.yml.
```

*What Happend?*
Clicked Sponsor Button
*Screenshots*
![image](https://user-images.githubusercontent.com/74466317/113342358-63e07380-92fc-11eb-8756-2b57f44cb65c.png)

**Comment by SolDevelop** [comment]
its fixed :) thanks for telling me!
